using ContextDepot.Domain.Exceptions;

namespace ContextDepot.Application.Shared.Exceptions;

public static class ApplicationErrorCodes
{
    public const string SettingsForbidden = "SettingsForbidden";
    public const string AccessKeyNotFound = "AccessKeyNotFound";
    public const string SettingsConflict = "SettingsConflict";
    public const string InvalidAiConfiguration = "InvalidAiConfiguration";
    public const string InvalidRequest = "InvalidRequest";
    public const string Unauthorized = "Unauthorized";
    public const string WebDepotUnavailable = "web.depot_unavailable";
    public const string WorkspacePathConflict = "workspace.path_conflict";
    public const string DataProtectionKeyRingInvalid = "DataProtectionKeyRingInvalid";
    public const string RetrievalConfigurationInvalid = "RetrievalConfigurationInvalid";
    public const string IndexRepairConfigurationInvalid = "IndexRepairConfigurationInvalid";
    public const string InvalidAppearanceTheme = "InvalidAppearanceTheme";
    public const string InvalidAppearanceLanguage = "InvalidAppearanceLanguage";
    public const string InvalidResourceQuery = "InvalidResourceQuery";
    public const string InternalError = "InternalError";
    public const string ContextNotFound = "ContextNotFound";
    public const string ContextConcurrencyConflict = "ContextConcurrencyConflict";
    public const string ContextWriteFailed = "ContextWriteFailed";
    public const string ContextKindConflict = "ContextKindConflict";
    public const string InvalidContextContent = "InvalidContextContent";
    public const string InvalidContextKind = "InvalidContextKind";
    public const string InvalidContextKey = "InvalidContextKey";
    public const string InvalidContextMetadata = "InvalidContextMetadata";
    public const string InvalidContextQuality = DomainErrorCodes.InvalidContextQuality;
    public const string InvalidContextValidity = DomainErrorCodes.InvalidContextValidity;
    public const string InvalidStateKey = "InvalidStateKey";
    public const string InvalidSupersedeTarget = "InvalidSupersedeTarget";
    public const string InvalidVerificationStatus = "InvalidVerificationStatus";
    public const string SecretContentRejected = "SecretContentRejected";
    public const string ContextTooLarge = "ContextTooLarge";
    public const string WorkspaceNotFound = "WorkspaceNotFound";
    public const string WorkspaceParentNotFound = "WorkspaceParentNotFound";
    public const string WorkspaceConcurrencyConflict = "WorkspaceConcurrencyConflict";
    public const string WorkspaceWriteFailed = "WorkspaceWriteFailed";
    public const string InvalidWorkspaceName = "InvalidWorkspaceName";
    public const string InvalidWorkspaceMetadata = "InvalidWorkspaceMetadata";
    public const string InvalidWorkspacePath = "InvalidWorkspacePath";
    public const string DocumentNotFound = "DocumentNotFound";
    public const string DocumentConflict = "DocumentConflict";
    public const string InvalidDocumentTitle = "InvalidDocumentTitle";
    public const string InvalidDocumentPath = "InvalidDocumentPath";
    public const string DocumentWriteFailed = "DocumentWriteFailed";
    public const string ContextBudgetInvalid = "ContextBudgetInvalid";
    public const string DatabaseMigrationFailed = "DatabaseMigrationFailed";
    public const string DatabaseUnavailable = "DatabaseUnavailable";
    public const string DesignTimeConfigurationMissing = "DesignTimeConfigurationMissing";
    public const string MarkdownRootUnavailable = "MarkdownRootUnavailable";
    public const string EmbeddingConfigurationInvalid = "EmbeddingConfigurationInvalid";
    public const string EmbeddingGeneratorUnavailable = "EmbeddingGeneratorUnavailable";
    public const string EmbeddingGeneratorInvalidResponse = "EmbeddingGeneratorInvalidResponse";
    public const string EmbeddingDimensionMismatch = "EmbeddingDimensionMismatch";
    public const string MarkdownFileMissing = "MarkdownFileMissing";
    public const string IndexRepairRequestInvalid = "IndexRepairRequestInvalid";
    public const string VectorSearchFailed = "VectorSearchFailed";
    public const string InvalidSearchQuery = "InvalidSearchQuery";
}
