<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
      <PackageReference Include="Microsoft.Extensions.VectorData.Abstractions" />
      <PackageReference Include="Npgsql" />
      <PackageReference Include="Pgvector" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
      <ProjectReference Include="..\ContextDepot.Application\ContextDepot.Application.csproj" />
      <ProjectReference Include="..\ContextDepot.Domain\ContextDepot.Domain.csproj" />
    </ItemGroup>

</Project>
