// <auto-generated />
using System;
using ContextDepot.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContextDepot.Infrastructure.Migrations
{
    [DbContext(typeof(ContextDepotDbContext))]
    [Migration("20260922232251_AddDatabaseManagedConfiguration")]
    partial class AddDatabaseManagedConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContextDepot.Domain.Contexts.ContextItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<short>("Importance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)50)
                        .HasColumnName("importance");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("ProvenanceTrust")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provenance_trust");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sensitivity");

                    b.Property<string>("SourceAgent")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_agent");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_ref");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("verification_status");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_context_items");

                    b.HasAlternateKey("Id", "DepotId", "WorkspaceId")
                        .HasName("ak_context_items_id_depot_id_workspace_id");

                    b.HasIndex("WorkspaceId", "DepotId");

                    b.HasIndex("DepotId", "WorkspaceId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_context_items_active_key")
                        .HasFilter("status = 'Active' AND key IS NOT NULL");

                    b.HasIndex("SupersedesId", "DepotId", "WorkspaceId");

                    b.ToTable("context_items", "public", t =>
                        {
                            t.HasCheckConstraint("ck_context_items_confidence", "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)");

                            t.HasCheckConstraint("ck_context_items_importance", "importance BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("ContextDepot.Domain.Depots.Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_depots");

                    b.ToTable("depots", "public");
                });

            modelBuilder.Entity("ContextDepot.Domain.Depots.DepotAccessKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_depot_access_keys");

                    b.HasAlternateKey("Id", "DepotId")
                        .HasName("ak_depot_access_keys_id_depot_id");

                    b.HasIndex("KeyPrefix")
                        .IsUnique()
                        .HasDatabaseName("ux_depot_access_keys_key_prefix");

                    b.HasIndex("DepotId", "Name")
                        .HasDatabaseName("ix_depot_access_keys_depot_name");

                    b.ToTable("depot_access_keys", "public");
                });

            modelBuilder.Entity("ContextDepot.Domain.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<string>("IndexStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("index_status");

                    b.Property<string>("IndexedContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("indexed_content_hash");

                    b.Property<string>("LastIndexError")
                        .HasColumnType("text")
                        .HasColumnName("last_index_error");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasAlternateKey("Id", "DepotId", "WorkspaceId")
                        .HasName("ak_documents_id_depot_id_workspace_id");

                    b.HasIndex("WorkspaceId", "DepotId");

                    b.HasIndex("DepotId", "WorkspaceId", "Path")
                        .IsUnique()
                        .HasDatabaseName("ux_documents_depot_workspace_path");

                    b.ToTable("documents", "public");
                });

            modelBuilder.Entity("ContextDepot.Domain.Documents.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("HeadingPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("heading_path");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_document_chunks");

                    b.HasIndex("DocumentId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_document_chunks_document_ordinal");

                    b.HasIndex("DocumentId", "DepotId", "WorkspaceId");

                    b.HasIndex("Id", "DepotId", "WorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("ux_document_chunks_id_depot_workspace");

                    b.ToTable("document_chunks", "public");
                });

            modelBuilder.Entity("ContextDepot.Domain.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentWorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_workspace_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasAlternateKey("Id", "DepotId")
                        .HasName("ak_workspaces_id_depot_id");

                    b.HasIndex("DepotId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_workspaces_root_slug")
                        .HasFilter("parent_workspace_id IS NULL");

                    b.HasIndex("ParentWorkspaceId", "DepotId");

                    b.HasIndex("DepotId", "ParentWorkspaceId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_workspaces_child_slug")
                        .HasFilter("parent_workspace_id IS NOT NULL");

                    b.ToTable("workspaces", "public");
                });

            modelBuilder.Entity("ContextDepot.Domain.Workspaces.WorkspaceAccessGrant", b =>
                {
                    b.Property<Guid>("DepotAccessKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_access_key_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.HasKey("DepotAccessKeyId", "WorkspaceId")
                        .HasName("pk_workspace_access_grants");

                    b.HasIndex("DepotAccessKeyId", "DepotId")
                        .HasDatabaseName("ix_workspace_access_grants_access_key_depot");

                    b.HasIndex("WorkspaceId", "DepotId")
                        .HasDatabaseName("ix_workspace_access_grants_workspace_depot");

                    b.ToTable("workspace_access_grants", "public");
                });

            modelBuilder.Entity("ContextDepot.Infrastructure.Configuration.ApplicationSettingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("NormalizedKey")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("normalized_key")
                        .HasComputedColumnSql("lower(key)", true);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_application_settings");

                    b.HasIndex("NormalizedKey")
                        .IsUnique()
                        .HasDatabaseName("ux_application_settings_normalized_key");

                    b.ToTable("application_settings", "public", t =>
                        {
                            t.HasCheckConstraint("ck_application_settings_value_scalar", "jsonb_typeof(value) IN ('string', 'number', 'boolean')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("01995f60-0000-7000-8000-000000000001"),
                            Key = "ContextDepot:Retrieval:Semantic:ScopeTopK",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "8"
                        },
                        new
                        {
                            Id = new Guid("01995f60-0000-7000-8000-000000000002"),
                            Key = "ContextDepot:Retrieval:Semantic:CandidateTopKPerSource",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "20"
                        },
                        new
                        {
                            Id = new Guid("01995f60-0000-7000-8000-000000000003"),
                            Key = "ContextDepot:Retrieval:Semantic:OversampleFactor",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "3"
                        },
                        new
                        {
                            Id = new Guid("01995f60-0000-7000-8000-000000000004"),
                            Key = "ContextDepot:Retrieval:Semantic:RetrievalLexicalFallbackThreshold",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "0.65"
                        },
                        new
                        {
                            Id = new Guid("01995f60-0000-7000-8000-000000000005"),
                            Key = "ContextDepot:Retrieval:Semantic:DedupSimilarityThreshold",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "0.98"
                        },
                        new
                        {
                            Id = new Guid("01995f60-0000-7000-8000-000000000006"),
                            Key = "ContextDepot:Retrieval:Semantic:DedupTokenOverlapThreshold",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "0.8"
                        },
                        new
                        {
                            Id = new Guid("01995f60-0000-7000-8000-000000000007"),
                            Key = "ContextDepot:Retrieval:Search:DefaultLimit",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "10"
                        },
                        new
                        {
                            Id = new Guid("01995f60-0000-7000-8000-000000000008"),
                            Key = "ContextDepot:Retrieval:Search:MaxLimit",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "50"
                        },
                        new
                        {
                            Id = new Guid("01995f60-0000-7000-8000-000000000009"),
                            Key = "ContextDepot:IndexRepair:PollIntervalSeconds",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "30"
                        },
                        new
                        {
                            Id = new Guid("01995f60-0000-7000-8000-000000000010"),
                            Key = "ContextDepot:IndexRepair:BatchSize",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "32"
                        },
                        new
                        {
                            Id = new Guid("01995f60-0000-7000-8000-000000000011"),
                            Key = "ContextDepot:IndexRepair:MaxBatchesPerCycle",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "4"
                        },
                        new
                        {
                            Id = new Guid("01995f60-0000-7000-8000-000000000012"),
                            Key = "ContextDepot:VectorCoverage:CacheDurationSeconds",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "30"
                        },
                        new
                        {
                            Id = new Guid("01995f60-0000-7000-8000-000000000013"),
                            Key = "ContextDepot:Appearance:Language",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "\"zh-CN\""
                        },
                        new
                        {
                            Id = new Guid("01995f60-0000-7000-8000-000000000014"),
                            Key = "ContextDepot:Appearance:Theme",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "\"system\""
                        });
                });

            modelBuilder.Entity("ContextDepot.Infrastructure.Configuration.InferenceProviderRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ProtectedApiKey")
                        .HasColumnType("text")
                        .HasColumnName("protected_api_key");

                    b.Property<string>("ProtocolCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("protocol_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("verification_state");

                    b.HasKey("Id")
                        .HasName("pk_inference_providers");

                    b.ToTable("inference_providers", "public", t =>
                        {
                            t.HasCheckConstraint("ck_inference_providers_protocol_code", "protocol_code = 'openai-compatible'");
                        });
                });

            modelBuilder.Entity("ContextDepot.Infrastructure.Configuration.InferenceRouteRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("capability");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Dimensions")
                        .HasColumnType("integer")
                        .HasColumnName("dimensions");

                    b.Property<string>("EmbeddingProfileFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("embedding_profile_fingerprint");

                    b.Property<long>("IndexGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("index_generation");

                    b.Property<string>("IndexState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("index_state");

                    b.Property<string>("ModelName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("model_name");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inference_routes");

                    b.HasIndex("Capability")
                        .IsUnique()
                        .HasDatabaseName("ux_inference_routes_capability");

                    b.HasIndex("ProviderId");

                    b.ToTable("inference_routes", "public", t =>
                        {
                            t.HasCheckConstraint("ck_inference_routes_capability", "capability IN ('chat', 'embedding')");

                            t.HasCheckConstraint("ck_inference_routes_dimensions", "(capability = 'chat' AND dimensions IS NULL) OR (capability = 'embedding' AND (model_name IS NULL OR dimensions > 0))");

                            t.HasCheckConstraint("ck_inference_routes_index_generation", "index_generation >= 0");

                            t.HasCheckConstraint("ck_inference_routes_provider_model_pair", "(provider_id IS NULL AND model_name IS NULL) OR (provider_id IS NOT NULL AND model_name IS NOT NULL)");

                            t.HasCheckConstraint("ck_inference_routes_timeout_seconds", "timeout_seconds BETWEEN 1 AND 300");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("01995f60-0000-7000-8000-000000000101"),
                            Capability = "chat",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IndexGeneration = 0L,
                            IndexState = "unconfigured",
                            TimeoutSeconds = 60,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("01995f60-0000-7000-8000-000000000102"),
                            Capability = "embedding",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IndexGeneration = 0L,
                            IndexState = "unconfigured",
                            TimeoutSeconds = 60,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ContextDepot.Domain.Contexts.ContextItem", b =>
                {
                    b.HasOne("ContextDepot.Domain.Workspaces.Workspace", "Workspace")
                        .WithMany("ContextItems")
                        .HasForeignKey("WorkspaceId", "DepotId")
                        .HasPrincipalKey("Id", "DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_context_items_workspaces_workspace_id_depot_id");

                    b.HasOne("ContextDepot.Domain.Contexts.ContextItem", "Supersedes")
                        .WithMany()
                        .HasForeignKey("SupersedesId", "DepotId", "WorkspaceId")
                        .HasPrincipalKey("Id", "DepotId", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_context_items_supersedes");

                    b.Navigation("Supersedes");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ContextDepot.Domain.Depots.DepotAccessKey", b =>
                {
                    b.HasOne("ContextDepot.Domain.Depots.Depot", "Depot")
                        .WithMany("AccessKeys")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_depot_access_keys_depot_id");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("ContextDepot.Domain.Documents.Document", b =>
                {
                    b.HasOne("ContextDepot.Domain.Workspaces.Workspace", "Workspace")
                        .WithMany("Documents")
                        .HasForeignKey("WorkspaceId", "DepotId")
                        .HasPrincipalKey("Id", "DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documents_workspaces_workspace_id_depot_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ContextDepot.Domain.Documents.DocumentChunk", b =>
                {
                    b.HasOne("ContextDepot.Domain.Documents.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId", "DepotId", "WorkspaceId")
                        .HasPrincipalKey("Id", "DepotId", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_chunks_documents_document_id_depot_id_workspace_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ContextDepot.Domain.Workspaces.Workspace", b =>
                {
                    b.HasOne("ContextDepot.Domain.Depots.Depot", "Depot")
                        .WithMany("Workspaces")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_depots_depot_id");

                    b.HasOne("ContextDepot.Domain.Workspaces.Workspace", "ParentWorkspace")
                        .WithMany("Children")
                        .HasForeignKey("ParentWorkspaceId", "DepotId")
                        .HasPrincipalKey("Id", "DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_workspaces_workspaces_parent_workspace_id_depot_id");

                    b.Navigation("Depot");

                    b.Navigation("ParentWorkspace");
                });

            modelBuilder.Entity("ContextDepot.Domain.Workspaces.WorkspaceAccessGrant", b =>
                {
                    b.HasOne("ContextDepot.Domain.Depots.DepotAccessKey", "AccessKey")
                        .WithMany("WorkspaceGrants")
                        .HasForeignKey("DepotAccessKeyId", "DepotId")
                        .HasPrincipalKey("Id", "DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_access_grants_access_key");

                    b.HasOne("ContextDepot.Domain.Workspaces.Workspace", "Workspace")
                        .WithMany("AccessKeyGrants")
                        .HasForeignKey("WorkspaceId", "DepotId")
                        .HasPrincipalKey("Id", "DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_access_grants_workspace");

                    b.Navigation("AccessKey");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ContextDepot.Infrastructure.Configuration.InferenceRouteRecord", b =>
                {
                    b.HasOne("ContextDepot.Infrastructure.Configuration.InferenceProviderRecord", "Provider")
                        .WithMany("Routes")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inference_routes_provider");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("ContextDepot.Domain.Depots.Depot", b =>
                {
                    b.Navigation("AccessKeys");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("ContextDepot.Domain.Depots.DepotAccessKey", b =>
                {
                    b.Navigation("WorkspaceGrants");
                });

            modelBuilder.Entity("ContextDepot.Domain.Documents.Document", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("ContextDepot.Domain.Workspaces.Workspace", b =>
                {
                    b.Navigation("AccessKeyGrants");

                    b.Navigation("Children");

                    b.Navigation("ContextItems");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ContextDepot.Infrastructure.Configuration.InferenceProviderRecord", b =>
                {
                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
