// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContextDepot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContextDepotDbContext))]
    partial class ContextDepotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContextDepot.Domain.Entities.ContextItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<short>("Importance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)50)
                        .HasColumnName("importance");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("ProvenanceTrust")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provenance_trust");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sensitivity");

                    b.Property<string>("SourceAgent")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_agent");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_ref");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("verification_status");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_context_items");

                    b.HasAlternateKey("Id", "OwnerId", "WorkspaceId")
                        .HasName("ak_context_items_id_owner_id_workspace_id");

                    b.HasIndex("WorkspaceId", "OwnerId");

                    b.HasIndex("OwnerId", "WorkspaceId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_context_items_active_key")
                        .HasFilter("status = 'Active' AND key IS NOT NULL");

                    b.HasIndex("SupersedesId", "OwnerId", "WorkspaceId");

                    b.ToTable("context_items", "public", t =>
                        {
                            t.HasCheckConstraint("ck_context_items_confidence", "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)");

                            t.HasCheckConstraint("ck_context_items_importance", "importance BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("ContextDepot.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IndexStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("index_status");

                    b.Property<string>("IndexedContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("indexed_content_hash");

                    b.Property<string>("LastIndexError")
                        .HasColumnType("text")
                        .HasColumnName("last_index_error");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasAlternateKey("Id", "OwnerId", "WorkspaceId")
                        .HasName("ak_documents_id_owner_id_workspace_id");

                    b.HasIndex("WorkspaceId", "OwnerId");

                    b.HasIndex("OwnerId", "WorkspaceId", "Path")
                        .IsUnique()
                        .HasDatabaseName("ux_documents_owner_workspace_path");

                    b.ToTable("documents", "public");
                });

            modelBuilder.Entity("ContextDepot.Domain.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("HeadingPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("heading_path");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_document_chunks");

                    b.HasIndex("DocumentId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_document_chunks_document_ordinal");

                    b.HasIndex("DocumentId", "OwnerId", "WorkspaceId");

                    b.HasIndex("Id", "OwnerId", "WorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("ux_document_chunks_id_owner_workspace");

                    b.ToTable("document_chunks", "public");
                });

            modelBuilder.Entity("ContextDepot.Domain.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_owners");

                    b.ToTable("owners", "public");
                });

            modelBuilder.Entity("ContextDepot.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("ParentWorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_workspace_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasAlternateKey("Id", "OwnerId")
                        .HasName("ak_workspaces_id_owner_id");

                    b.HasIndex("OwnerId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_workspaces_root_slug")
                        .HasFilter("parent_workspace_id IS NULL");

                    b.HasIndex("ParentWorkspaceId", "OwnerId");

                    b.HasIndex("OwnerId", "ParentWorkspaceId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_workspaces_child_slug")
                        .HasFilter("parent_workspace_id IS NOT NULL");

                    b.ToTable("workspaces", "public");
                });

            modelBuilder.Entity("ContextDepot.Domain.Entities.ContextItem", b =>
                {
                    b.HasOne("ContextDepot.Domain.Entities.Workspace", "Workspace")
                        .WithMany("ContextItems")
                        .HasForeignKey("WorkspaceId", "OwnerId")
                        .HasPrincipalKey("Id", "OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_context_items_workspaces_workspace_id_owner_id");

                    b.HasOne("ContextDepot.Domain.Entities.ContextItem", "Supersedes")
                        .WithMany()
                        .HasForeignKey("SupersedesId", "OwnerId", "WorkspaceId")
                        .HasPrincipalKey("Id", "OwnerId", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_context_items_supersedes");

                    b.Navigation("Supersedes");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ContextDepot.Domain.Entities.Document", b =>
                {
                    b.HasOne("ContextDepot.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Documents")
                        .HasForeignKey("WorkspaceId", "OwnerId")
                        .HasPrincipalKey("Id", "OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documents_workspaces_workspace_id_owner_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ContextDepot.Domain.Entities.DocumentChunk", b =>
                {
                    b.HasOne("ContextDepot.Domain.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId", "OwnerId", "WorkspaceId")
                        .HasPrincipalKey("Id", "OwnerId", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_chunks_documents_document_id_owner_id_workspace_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ContextDepot.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("ContextDepot.Domain.Entities.Owner", "Owner")
                        .WithMany("Workspaces")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_owners_owner_id");

                    b.HasOne("ContextDepot.Domain.Entities.Workspace", "ParentWorkspace")
                        .WithMany("Children")
                        .HasForeignKey("ParentWorkspaceId", "OwnerId")
                        .HasPrincipalKey("Id", "OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_workspaces_workspaces_parent_workspace_id_owner_id");

                    b.Navigation("Owner");

                    b.Navigation("ParentWorkspace");
                });

            modelBuilder.Entity("ContextDepot.Domain.Entities.Document", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("ContextDepot.Domain.Entities.Owner", b =>
                {
                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("ContextDepot.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ContextItems");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
